### PR TITLE
properly align user and group when listing mixed directories

### PR DESCRIPTION
**Pull request by anthraxx**
- this also fixes other small visual issues listed in your issues page
- its tested for a quite long time on my machine and several friends

its easy to observe via listing /tmp if you have different owner files in there:
```
ls++ --potsf -lAh --color /tmp
```

### CODE REVIEW

**Comment by glubsy** [comment]
Could be be more precise as to what fixes you added? 
Perhaps post a screenshot of the output? 
I've been working on a patch for aligning user and group too.

**Comment by anthraxx** [comment]
Besides the obvious user/group misalignment, it also fixes an edge case size misalignment depending on its length plus #31.

2017-06-02-153334_1920x1080_scrot

This patch set is in production and used by Arch Linux package for a quite long time now with all of its users being happy :stuck_out_tongue:

**Comment by glubsy** [comment]
Damn, your patch is nice indeed.
What happens if either the username or the group name is longer than the columns width? Does it make a mess or do you manage to have consistent column width? 

[My patch](https://github.com/trapd00r/ls--/pull/55) shrinks the long names but doesn't align the colon like yours. Good job man, I hope he merges your merge request! Sadly, trapd00r seems to be inactive lately. :(

**Comment by glubsy** [comment]
Oh I see you're the packager for Arch's repository. I'm using Antergos (and Arch Linux on a netbook).
Didn't realize you added your patch in that package. Glad you did. Thanks for that. 
Kudos to you for contributing to Arch. :heart:

**Comment by glubsy** [comment]
Here's how my test directory looks like with your patch, it's okay, but I like the shrinking feature. What's your take on it?

**Comment by anthraxx** [comment]
shrinking beyond the real length of a label would hide information (and i don't like hiding/cutting off :yum: ) so i prefer to live with long columns if there are long labels in a particular directory :smile_cat: 
Its also more convenient if i want to use the group/user label for something rather than having to resolve it to the full label somehow... but i see your point

Thanks, I appreciate the appreciation very much, you are welcome. I'm happy to serve the community :smile:

**Comment by glubsy** [comment]
There's still some alignment problems in some cases. Do you get the same output issues by listing /dev/ ?

ls++ --potsf /dev
ls++ --potsf /dev

That's the original ls++ output:
original ls++ --potsf /dev

Are you up to look into it, or should I try myself?

**Comment by trapd00r** [comment]
Oh wow, hey guys! 
Sorry I've been so inactive lately, let's blame it on family stuff happening. :)
This looks great, and I'm merging now. 
Thank you so much!

**Comment by glubsy** [comment]
He's alive! Thanks trapd00r! :D 

By the way, still not sure about the alignment issueb(looking into it), but I'm close to fixing the special files' size values. Might also fix the total size value while I'm at it. 
Will post patch soon.

**Comment by glubsy** [comment]
I fixed it. Now everything works great in all circumstances. :)
Submitting pull request.

**Pull request merged**
